INSERT INTO Category(CategoryID, Name) VALUES (0, "Sve kategorije");
INSERT INTO Category(CategoryID, Name) VALUES (1, "Matematika");
INSERT INTO Category(CategoryID, Name) VALUES (2, "Informatika");
INSERT INTO Category(CategoryID, Name) VALUES (3, "Fizika");
INSERT INTO Category(CategoryID, Name) VALUES (4, "Hemija");
INSERT INTO Category(CategoryID, Name) VALUES (5, "Biohemija");
INSERT INTO Category(CategoryID, Name) VALUES (6, "Zaštita životne sredine");
INSERT INTO Category(CategoryID, Name) VALUES (7, "Biologija");
INSERT INTO Category(CategoryID, Name) VALUES (8, "Ekologija");
INSERT INTO Category(CategoryID, Name) VALUES (9, "Geografija");
INSERT INTO Category(CategoryID, Name) VALUES (10, "Turizam");
INSERT INTO Category(CategoryID, Name) VALUES (11, "Hotelijerstvo");
INSERT INTO Category(CategoryID, Name) VALUES (12, "Administracija");
INSERT INTO Category(CategoryID, Name) VALUES (13, "Ostalo");